// src/create/component/PostFormCard.vue
<template>
  <form action="#" method="POST" class="card" @submit.prevent="$emit('submit', $event)" @reset="$emit('reset', $event)">
    <div class="card-title white-text pink lighten-1">{{ heading }}</div>
    <div class="card-content">
      <div class="input-field">
        <input id="title" type="text" required v-model="value.title">
        <label for="title">Title</label>
      </div>
      <div class="input-field">
        <textarea id="body" class="materialize-textarea" required v-model="value.body"></textarea>
        <label for="body">Body</label>
      </div>
      <div class="input-field">
        <datetime-local id="createdAt" required class="validate" v-model="value.createdAt"></datetime-local>
        <label for="createdAt" class="active">Created at</label>
      </div>
    </div>
    <div class="card-action">
      <slot></slot>
    </div>
  </form>
</template>

<script>
import DatetimeLocal from './DatetimeLocal.vue'

export default {
  props: {
    heading: String,
    value: Object
  },
  components: {
    'datetime-local': DatetimeLocal
  }
}
</script>

// packages/www/src/component/PostFormCard.tsx
import { Post } from '../PostTypes'
import React from 'react'
import { UseFormReturn } from 'react-hook-form'

export interface PostFormCardProps {
  readonly children: React.ReactNode
  readonly register: UseFormReturn<Post>['register']
  readonly formState: UseFormReturn<Post>['formState']
  readonly heading: string
  readonly handleSubmit: () => void
}

export const PostFormCard: React.FC<PostFormCardProps> = ({
  children,
  formState,
  heading,
  handleSubmit,
  register
}: PostFormCardProps) => (
  <form action="#" method="POST" className="card" onSubmit={handleSubmit}>
    <div className="card-title white-text pink lighten-1">{heading}</div>
    <div className="card-content">
      <div className="input-field">
        <input
          id="title"
          type="text"
          // eslint-disable-next-line react/jsx-props-no-spreading
          {...register('title', { required: true })}
        />
        <label htmlFor="title">Title</label>
      </div>
      <div className="input-field">
        <textarea
          id="body"
          className="materialize-textarea"
          // eslint-disable-next-line react/jsx-props-no-spreading
          {...register('body', { required: true })}
        />
        <label htmlFor="body">Body</label>
      </div>
      <div className="input-field">
        <input
          id="createdAt"
          type="text"
          // eslint-disable-next-line react/jsx-props-no-spreading
          {...register('createdAt', {
            pattern: /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/,
            required: true
          })}
        />
        <label htmlFor="createdAt" className="active">
          Created at
        </label>
        {formState.errors.createdAt && <span>Invalid date</span>}
      </div>
    </div>
    <div className="card-action">{children}</div>
  </form>
)
