// src/component/PostCards.tsx
import React from 'react';

interface Props {
  posts: {
    key: string
    title: string
    body: string
    createdAt: string
  }[]
}

function PostCards({ posts }: Props) {
  return (
    <div className="mdl-grid">
      {
        posts.map(post =>
          <div className="card" id={post.key}>
            <div className="card-title white-text pink lighten-1">{post.title}</div>
            <div className="card-content">
              {
                post.body.split('\n').map(line =>
                  <p>{line}</p>
                )
              }
              <p>{post.createdAt}</p>
            </div>
          </div>)
      }
    </div>
  )
}

export default PostCards

// src/partial/PostCards.vue
<template>
  <transition-group name="card" tag="section" class="mdl-grid" v-show="ready">
    <div class="card" v-for="post in posts" :id="post.key" :key="post">
      <div class="card-title amber darken-1">{{ post.title }}</div>
      <div class="card-content">
        <p v-for="line in post.body.split('\n')">{{ line }}</p>
        <p>{{ post.createdAt | date-localize }}</p>
      </div>
    </div>
  </transition-group>
</template>

<script>
export default {
  props: {
    posts: Array,
    ready: Boolean
  }
}
</script>
