// packages/www/src/component/LoginForm.tsx
import Modal from 'react-modal'
import React from 'react'
import { UseFormReturn } from 'react-hook-form'

export interface LoginFormProps {
  readonly register: UseFormReturn<{ email: string; password: string }>['register']
  readonly isOpen: boolean
  readonly handleSubmit: () => void
}

export const LoginForm: React.VFC<LoginFormProps> = ({
  isOpen,
  handleSubmit,
  register
}: LoginFormProps) => (
  <Modal isOpen={isOpen}>
    <div id="logindialog">
      <form action="#" method="POST" onSubmit={handleSubmit}>
        <div>
          <h4>Login</h4>
          <div className="row">
            <div className="input-field col s12">
              <input
                id="email"
                type="email"
                // eslint-disable-next-line react/jsx-props-no-spreading
                {...register('email', { required: true })}
              />
              <label htmlFor="email">Email</label>
            </div>
          </div>
          <div className="row">
            <div className="input-field col s12">
              <input
                id="password"
                type="password"
                // eslint-disable-next-line react/jsx-props-no-spreading
                {...register('password', { required: true })}
              />
              <label htmlFor="password">Password</label>
            </div>
          </div>
        </div>
        <div className="modal-footer">
          <button className="btn-flat" type="submit">
            Login
          </button>
        </div>
      </form>
    </div>
  </Modal>
)

// src/component/LoginForm.vue
<template>
  <div class="modal" id="logindialog">
    <form action="#" method="POST" @submit.prevent="$emit('submit', $event.target.elements.email.value, $event.target.elements.password.value)">
      <div class="modal-content">
        <h4>Login</h4>
        <div class="row">
          <div class="input-field col s12">
            <input id="email" type="email">
            <label for="email">Email</label>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <input id="password" type="password">
            <label for="password">Password</label>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn-flat" type="submit">Login</button>      
        <button class="btn-flat" @click="history.back()">Cancel</button>
      </div>
    </form>
  </div>
</template>

<script>
function mounted() {
  $(this.$el).modal({
    dismissible: false,
    inDuration: 0,
  })

  this.$watch('show', function (value) {
    $(this.$el).modal(value ? 'open' : 'close')
  }, {
    immediate: true
  })
}

export default {
  props: {
    show: Boolean
  },
  mounted: mounted
}
</script>
