// src/index/component/NotifySwitch.vue
<template>
  <div class="switch">
    <label>
      <input type="checkbox" :checked="enabled" @click="$emit('click', e)">
      <span class="lever"></span>
      {{ enabled ? '通知オン' : '通知オフ' }}
    </label>
  </div>
</template>

<script>
export default {
  props: {
    busy: Boolean,
    enabled: Boolean
  },
  watch: {
    busy: function (value) {
      this.$el.querySelector('input').disabled = value
    }
  }
}
</script>

// src/component/NotifySwitch.tsx
import React from 'react'

export interface Props {
  readonly busy: boolean
  readonly enabled: boolean
  readonly handleNotifyToggle: () => void
}

export const NotifySwitch = ({ busy, enabled, handleNotifyToggle }: Props) => (
  <div className="switch">
    <label>
      <input type="checkbox" checked={enabled} disabled={busy} onChange={handleNotifyToggle} />
      <span className="lever"></span>
      { enabled ? '通知オン' : '通知オフ' }
    </label>
  </div>
)
